[package]
name = "edge_drawer"
version = "0.1.0"
edition = "2021"


[dependencies]
image = "0.24"
imageproc = "0.23"
clap = "3.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
